name: CD / Publish release
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish release
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9-alpine

    steps:
      - name: Display build environment
        run: printenv
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Check that versions match in tag, readme and mix.exs
        run: mix run check_versions.exs
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs
      - name: Publish release
        if: (github.actor == 'TimPelgrim' || github.actor == 'EvertVerboven' || github.actor == 'juulSme')
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
