name: CI / Automated testing
on:
  push:
    branches:

jobs:
  ci_1_7:
    name: Elixir 1.7 CI
    runs-on: ubuntu-latest

    container:
      # alpine causes errors in the steps, the container exits immediately, apparently
      image: elixir:1.7-alpine
      env:
        MIX_ENV: test
        ELIXIR: "1.7"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: deps
          key: deps-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
            deps-${ELIXIR}-
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: _build
          key: build-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            build-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
            build-${ELIXIR}
      - name: Display build environment
        run: printenv
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs
      - name: Run dialyzer
        run: mix dialyzer

  ci_1_9:
    name: Elixir 1.9 CI
    runs-on: ubuntu-latest

    container:
      # alpine causes errors in the steps, the container exits immediately, apparently
      image: elixir:1.9-alpine
      env:
        MIX_ENV: test
        ELIXIR: "1.9"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: deps
          key: deps-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
            deps-${ELIXIR}-
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: _build
          key: build-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            build-${ELIXIR}-${{ hashFiles('**/mix.lock') }}
            build-${ELIXIR}
      - name: Display build environment
        run: printenv
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs
      - name: Run dialyzer
        run: mix dialyzer
